/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.financeiro.frmCompromissos;

/**
 *
 * @author luiz
 */
public class frmCompromisso extends javax.swing.JFrame {

    /**
     * Creates new form frmCompromisso
     */
    public frmCompromisso() {
        initComponents();
        limparCamposCompromisso();
        travarCamposCompromisso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescritivoDoFormulário = new javax.swing.JLabel();
        lbl_Id = new javax.swing.JLabel();
        tf_Id = new javax.swing.JTextField();
        lbl_DataCadastro = new javax.swing.JLabel();
        tf_dataCadastro = new javax.swing.JTextField();
        lbl_dataVencimento = new javax.swing.JLabel();
        tf_dataVencimento = new javax.swing.JTextField();
        lbl_valor = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cb_fornecedor = new javax.swing.JComboBox<>();
        tf_fornecedor = new javax.swing.JTextField();
        lbl_documento = new javax.swing.JLabel();
        tf_documento = new javax.swing.JTextField();
        lbl_parcela = new javax.swing.JLabel();
        tf_parcela = new javax.swing.JTextField();
        lbl_codigodeBarras = new javax.swing.JLabel();
        tf_codigodeBarras = new javax.swing.JTextField();
        lbl_observacao = new javax.swing.JLabel();
        sp_observacao = new javax.swing.JScrollPane();
        ta_observacao = new javax.swing.JTextArea();
        lbl_dataPagamento = new javax.swing.JLabel();
        lbl_pagamentoEfetuado = new javax.swing.JLabel();
        tf_dataPagamento = new javax.swing.JTextField();
        chb_pagamentoEfetuado = new javax.swing.JCheckBox();
        btn_novo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DescritivoDoFormulário.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        DescritivoDoFormulário.setForeground(new java.awt.Color(255, 0, 0));
        DescritivoDoFormulário.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescritivoDoFormulário.setText("Compromissos");
        DescritivoDoFormulário.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_Id.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_Id.setText("Id:");

        tf_Id.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_Id.setText("jTextField1");

        lbl_DataCadastro.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_DataCadastro.setText("Data Cadastro:");

        tf_dataCadastro.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_dataCadastro.setText("jTextField1");

        lbl_dataVencimento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_dataVencimento.setText("Data Vencimento:");

        tf_dataVencimento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_dataVencimento.setText("jTextField1");

        lbl_valor.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_valor.setText("Valor:");

        tf_valor.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_valor.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Fornecedor:");

        cb_fornecedor.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        cb_fornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tf_fornecedor.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_fornecedor.setText("jTextField1");

        lbl_documento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_documento.setText("Documento:");
        lbl_documento.setToolTipText("Número do pedido ou nota fiscal que gerou a dívida");

        tf_documento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_documento.setText("jTextField1");

        lbl_parcela.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_parcela.setText("Parcela:");

        tf_parcela.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_parcela.setText("jTextField1");
        tf_parcela.setToolTipText("número da parcela do boleto caso existam várias parcelas relacionadas à mesma nota fiscal ou pedido");

        lbl_codigodeBarras.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_codigodeBarras.setText("Código de barras:");

        tf_codigodeBarras.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_codigodeBarras.setText("jTextField1");
        tf_codigodeBarras.setToolTipText("Digite ou digitalize o código de barras do boleto se puder");

        lbl_observacao.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_observacao.setText("Observações:");

        ta_observacao.setColumns(20);
        ta_observacao.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        ta_observacao.setRows(5);
        sp_observacao.setViewportView(ta_observacao);

        lbl_dataPagamento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_dataPagamento.setText("Data Pagamento:");

        lbl_pagamentoEfetuado.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lbl_pagamentoEfetuado.setText("Pagamento efetuado:");

        tf_dataPagamento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tf_dataPagamento.setText("jTextField1");

        chb_pagamentoEfetuado.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        chb_pagamentoEfetuado.setText("SIM");

        btn_novo.setMnemonic('N');
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescritivoDoFormulário, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_pagamentoEfetuado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chb_pagamentoEfetuado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_dataPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_observacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sp_observacao))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_codigodeBarras)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_codigodeBarras))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl_documento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_documento))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_Id)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_DataCadastro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_dataVencimento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_dataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_valor)
                                .addComponent(lbl_parcela))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_parcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(DescritivoDoFormulário)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Id)
                    .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DataCadastro)
                    .addComponent(tf_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataVencimento)
                    .addComponent(tf_dataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valor)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_documento)
                    .addComponent(tf_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_parcela)
                    .addComponent(tf_parcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigodeBarras)
                    .addComponent(tf_codigodeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_observacao)
                    .addComponent(sp_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dataPagamento)
                    .addComponent(tf_dataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pagamentoEfetuado)
                    .addComponent(chb_pagamentoEfetuado))
                .addGap(18, 18, 18)
                .addComponent(btn_novo)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        
    }//GEN-LAST:event_btn_novoActionPerformed
    
    public void limparCamposCompromisso()
    {
    tf_Id.setText(" ");
    tf_codigodeBarras.setText("");
    tf_dataCadastro.setText("");
    tf_dataPagamento.setText("");
    tf_dataVencimento.setText("");
    tf_documento.setText("");
    tf_fornecedor.setText("");
    tf_parcela.setText("      ");
    tf_valor.setText("       ");
    ta_observacao.setText("");
    }
    
    public void travarCamposCompromisso()
    {
    tf_Id.setEnabled(false);
    tf_codigodeBarras.setEnabled(false);
    tf_dataCadastro.setEnabled(false);
    tf_dataPagamento.setEnabled(false);
    tf_dataVencimento.setEnabled(false);
    tf_documento.setEnabled(false);
    tf_fornecedor.setEnabled(false);
    tf_parcela.setEnabled(false);
    tf_valor.setEnabled(false);
    ta_observacao.setEnabled(false);
    cb_fornecedor.setEnabled(false);
    chb_pagamentoEfetuado.setEnabled(false);
    ta_observacao.setEnabled(false);
    }
    
    public void liberarCamposCompromisso()
    {
    tf_Id.setEnabled(true);
    tf_codigodeBarras.setEnabled(true);
    tf_dataCadastro.setEnabled(true);
    tf_dataPagamento.setEnabled(true);
    tf_dataVencimento.setEnabled(true);
    tf_documento.setEnabled(true);
    tf_fornecedor.setEnabled(true);
    tf_parcela.setEnabled(true);
    tf_valor.setEnabled(true);
    ta_observacao.setEnabled(true);
    cb_fornecedor.setEnabled(true);
    chb_pagamentoEfetuado.setEnabled(true);
    ta_observacao.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompromisso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescritivoDoFormulário;
    private javax.swing.JButton btn_novo;
    private javax.swing.JComboBox<String> cb_fornecedor;
    private javax.swing.JCheckBox chb_pagamentoEfetuado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_DataCadastro;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_codigodeBarras;
    private javax.swing.JLabel lbl_dataPagamento;
    private javax.swing.JLabel lbl_dataVencimento;
    private javax.swing.JLabel lbl_documento;
    private javax.swing.JLabel lbl_observacao;
    private javax.swing.JLabel lbl_pagamentoEfetuado;
    private javax.swing.JLabel lbl_parcela;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JScrollPane sp_observacao;
    private javax.swing.JTextArea ta_observacao;
    private javax.swing.JTextField tf_Id;
    private javax.swing.JTextField tf_codigodeBarras;
    private javax.swing.JTextField tf_dataCadastro;
    private javax.swing.JTextField tf_dataPagamento;
    private javax.swing.JTextField tf_dataVencimento;
    private javax.swing.JTextField tf_documento;
    private javax.swing.JTextField tf_fornecedor;
    private javax.swing.JTextField tf_parcela;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
