/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.financeiro.frmFornecedores;

import com.mycompany.financeiro.dao.fornecedores;
import com.mycompany.financeiro.dao.utilidades.conexao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz.souza
 */
public class frmFornecedores extends javax.swing.JFrame {
    public int posicaoFornecedores;
    List<fornecedores> fornecedores = new ArrayList<>();
    public ResultSet resultado;
    public int codigo;
    /**
     * Creates new form frmFornecedores
     */
    public frmFornecedores() {
        initComponents();
        fornecedores=carregaFornecedores();
        mostrarFornecedores(fornecedores);
    }
public List<fornecedores> carregaFornecedores(){
        conexao con = new conexao();
        con.conecta();
        resultado = con.executaConsulta("select * from fornecedores");
        System.out.print("\nEntrei no carregaFornecedores() \n");
        
        try
        {
        while (resultado.next())
        {
            System.out.print("\n Entrei no while do carregaFornecedores()\n");
            System.out.print("\nResultado: " + resultado.toString());
            fornecedores atual = new fornecedores();
            atual.setEnderecoFornecedor(resultado.getString("EnderecoFornecedor"));
            atual.setIdFornecedor(resultado.getInt("IdFornecedor"));
            atual.setNomeFornecedor(resultado.getString("NomeFornecedor"));
            atual.setFoneFornecedor(resultado.getString("FoneFornecedor"));
            atual.setObservacoesfornecedor(resultado.getString("Observacoesfornecedor"));
        fornecedores.add(atual);
        System.out.print("\nLendo registros: "+fornecedores.size());
        }
        System.out.print("\nSaindo do while: ");
        }
    catch (SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
     posicaoFornecedores=0;
     System.out.print("\nRegistros lidos: "+fornecedores.size());
     return fornecedores;
        }
public void mostrarFornecedores(List<fornecedores> fornecedores)
{
    if ((fornecedores.size()-1)<1)
    {
    JOptionPane.showMessageDialog(null, "Não há registros suficientes para exibição "+(fornecedores.size()-1));
    }
    else
    {
    System.out.print("\nposicao:"+posicaoFornecedores+"\n");
    tf_Id.setText(String.valueOf(fornecedores.get(posicaoFornecedores).getIdFornecedor()));
    tf_Nome.setText(fornecedores.get(posicaoFornecedores).getNomeFornecedor());
    tf_Endereco.setText(fornecedores.get(posicaoFornecedores).getEnderecoFornecedor());
    tf_Fone.setText(fornecedores.get(posicaoFornecedores).getFoneFornecedor());
    tf_Observacao.setText(fornecedores.get(posicaoFornecedores).getObservacoesfornecedor());
    lbl_posicao.setText(String.valueOf(posicaoFornecedores));
    }   

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Id = new javax.swing.JTextField();
        tf_Nome = new javax.swing.JTextField();
        tf_Endereco = new javax.swing.JTextField();
        tf_Fone = new javax.swing.JTextField();
        lbl_Id = new javax.swing.JLabel();
        lbl_Nome = new javax.swing.JLabel();
        lbl_Endereco = new javax.swing.JLabel();
        lbl_Fone = new javax.swing.JLabel();
        btn_Anterior = new javax.swing.JButton();
        btn_Proximo = new javax.swing.JButton();
        lbl_Obs = new javax.swing.JLabel();
        tf_Observacao = new javax.swing.JTextField();
        btn_Ultimo = new javax.swing.JToggleButton();
        btn_Primeiro = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_posicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Id.setText("jTextField1");

        tf_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Nome.setText("jTextField2");

        tf_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Endereco.setText("jTextField3");

        tf_Fone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Fone.setText("jTextField4");

        lbl_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Id.setText("ID:");

        lbl_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Nome.setText("Nome:");

        lbl_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Endereco.setText("Endereço:");

        lbl_Fone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Fone.setText("Fone:");

        btn_Anterior.setText("Anterior");
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Proximo.setText("Próximo");
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        lbl_Obs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Obs.setText("Observação:");

        tf_Observacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Observacao.setText("jTextField5");

        btn_Ultimo.setText("Último");
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        btn_Primeiro.setText("Primeiro");
        btn_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroActionPerformed(evt);
            }
        });

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_posicao.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Novo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addComponent(btn_Primeiro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Anterior)
                        .addGap(29, 29, 29)
                        .addComponent(btn_Proximo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Ultimo)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_Obs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Observacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Endereco)
                            .addComponent(lbl_Fone)
                            .addComponent(lbl_Nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Nome)
                            .addComponent(tf_Fone)
                            .addComponent(tf_Endereco))))
                .addGap(31, 31, 31)
                .addComponent(lbl_posicao)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Id)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_posicao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Fone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Obs)
                    .addComponent(tf_Observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ultimo)
                    .addComponent(btn_Proximo)
                    .addComponent(btn_Anterior)
                    .addComponent(btn_Primeiro)
                    .addComponent(btn_Novo)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
   if (posicaoFornecedores<fornecedores.size()-1)
        posicaoFornecedores=posicaoFornecedores+1;
        
            mostrarFornecedores(fornecedores);
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
if (posicaoFornecedores>0)
    posicaoFornecedores=posicaoFornecedores-1;
        mostrarFornecedores(fornecedores);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroActionPerformed
    posicaoFornecedores=0;
        mostrarFornecedores(fornecedores);
    }//GEN-LAST:event_btn_PrimeiroActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
    posicaoFornecedores=fornecedores.size()-1;
        mostrarFornecedores(fornecedores);
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
    limpaCamposFornecedores();
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    codigo= pegaUltimoCodigoFornecedores()+1;
    System.out.print(codigo);
        String SQL = "Insert into fornecedores (IdFornecedor,NomeFornecedor,FoneFornecedor,EnderecoFornecedor,ObservacoesFornecedor) values ("+codigo+",'"+
            tf_Nome.getText()+"','"+tf_Fone.getText()+"','"+tf_Endereco.getText()+"','"+tf_Observacao.getText()+"')";
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate(SQL);
    limpaCamposFornecedores();
    carregaFornecedores();
    mostrarFornecedores(fornecedores);
    }//GEN-LAST:event_jButton1ActionPerformed

    public int pegaUltimoCodigoFornecedores()
        {
         conexao con = new conexao();
         con.executaConsulta("Select IdFornecedor from fornecedores order by IdFornecedor");
         try
         {
         codigo = (fornecedores.size()-1);
         System.out.print("\n Ultimo codigo:"+codigo);
         }
         catch (Exception e)
         {
         JOptionPane.showMessageDialog(null, e);
         }
        System.out.print("\npegaUltimoCodigoForenecedores: "+codigo+"\n");
         return codigo;
        }
    /**
     * @param args the command line arguments
     */
    public void limpaCamposFornecedores()
    { 
    tf_Id.setText("");
    tf_Nome.setText("");
    tf_Endereco.setText("");
    tf_Fone.setText("");
    tf_Observacao.setText("");
    tf_Nome.requestFocus();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Primeiro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JToggleButton btn_Ultimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_Fone;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Obs;
    private javax.swing.JLabel lbl_posicao;
    private javax.swing.JTextField tf_Endereco;
    private javax.swing.JTextField tf_Fone;
    private javax.swing.JTextField tf_Id;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_Observacao;
    // End of variables declaration//GEN-END:variables
}

